name: Keep Alive

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Curl Healhcheck
        run: curl -I https://lovely-api-38om.onrender.com/health
